import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen min-h-screen">
      <Providers>
        <body className="w-full min-h-screen mx-auto">
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
