const reviews = [
    {
      id: "rev-001",
      user: "Emily Johnson",
      rating: 5,
      comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      date: "2024-01-15",
      verifiedPurchase: true,
    },
    {
      id: "rev-002",
      user: "Michael Smith",
      rating: 4,
      comment: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      date: "2024-02-03",
      verifiedPurchase: true,
    },
    {
      id: "rev-003",
      user: "Sophia Williams",
      rating: 3,
      comment: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      date: "2024-01-25",
      verifiedPurchase: false,
    },
    {
      id: "rev-004",
      user: "James Anderson",
      rating: 5,
      comment: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      date: "2024-02-10",
      verifiedPurchase: true,
    },
    {
      id: "rev-005",
      user: "Olivia Martinez",
      rating: 4,
      comment: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec velit neque.",
      date: "2024-03-01",
      verifiedPurchase: false,
    },
    {
      id: "rev-006",
      user: "Daniel Thompson",
      rating: 2,
      comment: "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Vivamus suscipit tortor eget felis porttitor volutpat.",
      date: "2024-03-08",
      verifiedPurchase: true,
    },
    {
      id: "rev-007",
      user: "Emma Wilson",
      rating: 5,
      comment: "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Mauris blandit aliquet elit.",
      date: "2024-03-12",
      verifiedPurchase: true,
    },
    {
      id: "rev-008",
      user: "David Lee",
      rating: 3,
      comment: "Sed porttitor lectus nibh. Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt.",
      date: "2024-03-20",
      verifiedPurchase: false,
    },
    {
      id: "rev-009",
      user: "Charlotte Brown",
      rating: 4,
      comment: "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
      date: "2024-03-22",
      verifiedPurchase: true,
    },
    {
      id: "rev-010",
      user: "Ethan Walker",
      rating: 1,
      comment: "Pellentesque in ipsum id orci porta dapibus. Quisque velit nisi, pretium ut lacinia in, elementum id enim.",
      date: "2024-03-25",
      verifiedPurchase: false,
    }
  ];
  
  export default reviews;